name: magec
channels:
 - defaults
 - anaconda
 - conda-forge
 - intel
 - gwerbin
 - plotly
dependencies:
 - python=3.7
 - pandas=0.25
 - scikit-learn
 - jupyter
 - keras
 - pydot
 - matplotlib
 - xlrd
 - pandas-profiling
 - s3fs
 - deprecated
 - adjusttext
 - psycopg2
 - sqlalchemy
 - seaborn
 - plotly
